spring.application.name=Tenant-Provisioning-Service
server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5432/invox_db
spring.datasource.username=postgres
spring.datasource.password=post1234
spring.jpa.hibernate.ddl-auto=update

asgardeo.org-name=${ORG_NAME}
asgardeo.client-id=${M2M_CLIENT_ID}
asgardeo.client-secret=${M2M_CLIENT_SECRET}
asgardeo.token-url=https://api.asgardeo.io/t/${ORG_NAME}/oauth2/token
asgardeo.scim-group-url=https://api.asgardeo.io/t/${ORG_NAME}/scim2/Groups
asgardeo.admin-role-id=${ADMIN_ROLE_ID}