server:
  port: 8085

spring:
  application:
    name: customer-service

  datasource:
    url: jdbc:postgresql://localhost:5432/invox_db
    username: postgres
    password: ${DB_PASSWORD:post1234}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.invox.customer_service: DEBUG
    org.springframework.security: INFO
