server:
  port: 8081

spring:
  application:
    name: tenant-service
  config:
    import:
      - optional:file:.env[.properties]
      - optional:file:../../.env[.properties]
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/invox_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: ${SMTP_HOST:smtp.gmail.com}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USERNAME:}
    password: ${SMTP_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://api.asgardeo.io/t/${asgardeo.root-org:pixelaura}/oauth2/jwks

asgardeo:
  root-org: ${ASGARDEO_ROOT_ORG:invox1}
  token-endpoint: https://api.asgardeo.io/t/${asgardeo.root-org:invox1}/oauth2/token
  base-api-url: https://api.asgardeo.io/t/${asgardeo.root-org:invox1}/api/server/v1
  client-id: ${ASGARDEO_CLIENT_ID:}
  client-secret: ${ASGARDEO_CLIENT_SECRET:}
  spa-client-id: ${ASGARDEO_SPA_CLIENT_ID:}
  scopes: >-
    internal_organization_create
    internal_organization_view

management:
  endpoints:
    web:
      exposure:
        include: health,info
