spring.application.name=invox

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://api.asgardeo.io/t/invox1/oauth2/token
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://api.asgardeo.io/t/invox1/oauth2/jwks

logging.level.org.springframework.security=TRACE
logging.level.org.springframework.boot.autoconfigure.security=DEBUG